export const mokNewComputersData = [
    {
        id: 12,
        name: "HYPERPC LUMEN MAX",
        image: require("./assets/newproducts/1.jpg"),
        description:
            "Мощная платформа для ультимативного 2К-гейминга с видеокартой NVIDIA GeForce RTX 3080 [10GB, 8704 CUDA] и процессором Intel® Core™ i7-12700(F) [до 4.9GHz, 12 ядер].",
        rating: 5,
        processor: "Intel Core i7-12700F",
        memory: "DDR4",
        memoryCount: "32 GB",
        videoCard: "NVIDIA GeForce RTX 3080",
        videoCardMemory: "10 GB",
        SSD: "2000 GB",
        price: "309 900",
    },
    {
        id: 13,
        name: "HYPERPC AMPERE",
        image: require("./assets/newproducts/2.jpg"),
        description:
            "Один из самых мощных игровых компьютеров HYPERPC AMPERE. Уникальная конструкциия несет в себе видеоускоритель NVIDIA GeForce RTX 4090 [24GB, 16384 CUDA] и процессор AMD Ryzen 9 7950X [до 5.7GHz, 16 ядер].",
        rating: 4.5,
        processor: "AMD Ryzen 9 7950X",
        memory: "DDR4",
        memoryCount: "8 GB",
        videoCard: "NVIDIA GeForce RTX 4090",
        videoCardMemory: "64 GB",
        SSD: "2000 GB",
        price: "1 345 999",
    },
    {
        id: 14,
        name: "HYPERPC GENESIS",
        image: require("./assets/newproducts/3.jpg"),
        description:
            "Мощный игровой концепт с системой жидкостного охлаждения для ААА-игр с графикой “Ультра”. Внутри ПК установлены видеокарта NVIDIA GeForce RTX 4080 [16GB, 9728 CUDA] и процессор Intel® Core™ i7-13700K(F) [до 5.4GHz, 16 ядер].",
        rating: 4.5,
        processor: "Intel Core i7-13700KF",
        memory: "DDR4",
        memoryCount: "32 GB",
        videoCard: "NVIDIA GeForce RTX 4080",
        videoCardMemory: "16 GB",
        SSD: "2000 GB",
        price: "789 999",
    },
    {
        id: 15,
        name: "HYPERPC CYBER",
        image: require("./assets/newproducts/4.jpg"),
        description:
            "Стильный и производительный игровой компьютер с видеокартой NVIDIA GeForce RTX 4070 Ti [12GB, 7680 CUDA] и процессором Intel® Core™ i7-13700K(F) [до 5.4GHz, 16 ядер].",
        rating: 3.5,
        processor: "Intel Core i7-13700KF",
        memory: "DDR4",
        memoryCount: "32 GB",
        videoCard: "NVIDIA GeForce RTX 4070 Ti",
        videoCardMemory: "12 GB",
        SSD: "1000 GB",
        price: "307 999",
    },
];
