export const mokСomputersData = [
    {
        id: 1,
        name: "MSI MAG Infinite S3 11SC-213XRU",
        image: require("./assets/computers/2.jpg"),
        description:
            "ПК MSI MAG Infinite S3 11SC-213XRU [9S6-B93811-213] на базе процессора Intel Core i5 11-го поколения обеспечит вам возможность прокачать свои достижения в гейминге. У него есть оперативная память объемом 16 ГБ и дискретная видеокарта GeForce RTX 2060. Вся эта конфигурация заключена в среднеразмерный корпус форм-фактора Mid-Tower с ассиметричными линиями и встроенной подсветкой Mystic Light. Его можно назвать не только функциональным, но и привлекательным. За эффективную вентиляцию отвечают большие воздухозаборники. Накопитель ПК MSI MAG Infinite S3 11SC-213XRU [9S6-B93811-213] рассчитан на размещение до 512 ГБ программ, игр и файлов.",
        rating: 5,
        processor: "Intel Core i5-11400F",
        memory: "DDR4",
        memoryCount: "16 GB",
        videoCard: "GeForce RTX 2060",
        videoCardMemory: "6 GB",
        SSD: "512 GB",
        price: "64 999",
    },
    {
        id: 2,
        name: "ZET GAMING NEO M062",
        image: require("./assets/computers/1.jpg"),
        description:
            "ПК ZET Gaming NEO M062 представлен в форм-факторе Mid-Tower и имеет классическую черную расцветку корпуса. Лаконичный дизайн и оптимальная производительность делают данную модель подходящей для любого геймера. Процессор в компьютере представлен 4-ядерной моделью Intel Core i3-10105F. Для быстродействия при работе в многозадачном режиме имеется 8 ГБ оперативной памяти.",
        rating: 4.5,
        processor: "Intel Core i3-10105F",
        memory: "DDR4",
        memoryCount: "8 GB",
        videoCard: "GeForce GTX 1650",
        videoCardMemory: "4 GB",
        SSD: "512 GB",
        price: "40 999",
    },
    {
        id: 3,
        name: "ZET GAMING NEO M027",
        image: require("./assets/computers/3.jpg"),
        description:
            "ПК ZET Gaming NEO M027 в черном корпусе Mid-Tower поставляется без ОС. Лаконичный дизайн и оптимальная производительность делают данную модель подходящей для любого геймера. Получив процессор Intel Core i3-10100F и 16 ГБ оперативной памяти, компьютер вывозит самые мощные игры. Для хранения программного обеспечения, мультимедийных файлов и документов ПК может предложить до 500 ГБ места на шустром SSD-диске.",
        rating: 4.5,
        processor: "Intel Core i3-10100F",
        memory: "DDR4",
        memoryCount: "16 GB",
        videoCard: "GeForce GTX 1550 Ti",
        videoCardMemory: "4 GB",
        SSD: "512 GB",
        price: "38 999",
    },
    {
        id: 4,
        name: "ARDOR GAMING NEO M093",
        image: require("./assets/computers/5.jpg"),
        description:
            "ПК ARDOR GAMING NEO M093 представлен в форм-факторе Mid-Tower и имеет классическую черную расцветку корпуса. Лаконичный дизайн и оптимальная производительность делают данную модель подходящей для любого геймера. Процессор в компьютере представлен 6-ядерной моделью Intel Core i5-12400F. Для быстродействия при работе в многозадачном режиме имеется 16 ГБ оперативной памяти. За изображение отвечает видеокарта MSI GeForce RTX 3050 VENTUS 2X OC.",
        rating: 4.5,
        processor: "Intel Core i5-12400F",
        memory: "DDR4",
        memoryCount: "16 GB",
        videoCard: "GeForce RTX 3050",
        videoCardMemory: "8 GB",
        SSD: "512 GB",
        price: "64 999",
    },
    {
        id: 5,
        name: "MSI Trident 3 A 11SI-076XRU",
        image: require("./assets/computers/7.jpg"),
        description:
            "MSI Trident 3 A 11SI-076XRU – это мощный мини-компьютер геймерского класса с процессором Intel Core 11-го поколения. Элегантный дизайн и возможность вертикальной установки на подставку делают его идеальным устройством для домашней обстановки.",
        rating: 5,
        processor: "Intel Core i5-11400F",
        memory: "DDR4",
        memoryCount: "8 GB",
        videoCard: "GeForce GTX 1660 SUPER",
        videoCardMemory: "6 GB",
        SSD: "512 GB",
        price: "91 499",
    },
    {
        id: 6,
        name: "HP Pavilion Gaming TG01-2080UR",
        image: require("./assets/computers/8.jpg"),
        description:
            "Будь готов к игре на твоих условиях. Это мощное устройство HP Pavilion Gaming TG01 создано, чтобы справляться с самыми требовательными играми как сегодня, так и завтра. Этот компактный и изящный корпус скрывает мощные компоненты, позволяющие играть с уверенностью, а также пространство для расширения и модернизации.",
        rating: 3,
        processor: "AMD Ryzen 5 5600G",
        memory: "DDR4",
        memoryCount: "16 GB",
        videoCard: "Radeon RX 6600 XT",
        videoCardMemory: "8 GB",
        SSD: "512 GB",
        price: "97 299",
    },
    {
        id: 7,
        name: "ZET GAMING WARD H223",
        image: require("./assets/computers/9.jpg"),
        description:
            "ПК ZET GAMING WARD H223 является мощной игровой моделью с процессором Intel Core i7-12700KF, видеокартой GeForce RTX 3070 и 16 ГБ оперативной памятью. SSD-накопитель рассчитан на размещение до 1 ТБ информации. Вся эта начинка заключена в корпус формата Mid-Tower с окном в боковой стенке. Он выполнен в черно-серебристой расцветке и дополнен кулерами с подсветкой. Возможность форсированной работы при высоких нагрузках и при этом достойная скорость функционирования – все это ПК ZET GAMING WARD H223. Устройство дополнено ОС Windows 11 Home Single Language.",
        rating: 4.7,
        processor: "Intel Core i7-12700KF",
        memory: "DDR4",
        memoryCount: "16 GB",
        videoCard: "GeForce RTX 3070",
        videoCardMemory: "8 GB",
        SSD: "1000 GB",
        price: "149 999",
    },
    {
        id: 8,
        name: "ASUS ROG Strix G15CE-51140F0370",
        image: require("./assets/computers/10.jpg"),
        description:
            "Боевая станция Asus G15CE – весомое преимущество в киберспортивных дисциплинах. Разработанный специально для того, чтобы обеспечить максимально плавную игровую картинку, этот компактный компьютер обладает мощной конфигурацией, в которую входит видеокарта NVIDIA GeForce и процессор Intel Core 11 поколения.",
        rating: 4.5,
        processor: "Intel Core i5-11400F",
        memory: "DDR4",
        memoryCount: "16 GB",
        videoCard: "GeForce RTX 3080",
        videoCardMemory: "10 GB",
        SSD: "512 GB",
        price: "177 999",
    },
    {
        id: 9,
        name: "ASUS ROG Strix G10CE-711700073W",
        image: require("./assets/computers/11.jpg"),
        description:
            "ASUS ROG Strix G10CE – сочетание высокой производительности с неповторимым дизайном. В аппаратную конфигурацию этого игрового компьютера, входят процессор Intel Core i7, видеокарта NVIDIA GeForce RTX 3070, высокоскоростной беспроводной адаптер Intel Wi-Fi 802.11ac, твердотельный накопитель (M.2, PCIe) и опциональная память Intel Optane. Благодаря прозрачной боковой панели и синхронизируемой подсветке Aura пользователь может легко персонализировать внешний вид устройства по своему вкусу.",
        rating: 4.5,
        processor: "Intel Core i7-11700",
        memory: "DDR4",
        memoryCount: "16 GB",
        videoCard: "GeForce RTX 3070",
        videoCardMemory: "8 GB",
        SSD: "512 GB",
        price: "188 999",
    },
];
